ShopApp.WebUI/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstract;
using ShopApp.WebUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ShopApp.WebUI.Controllers
{
    public class ShopController : Controller
    {
        /* shop controller is for user pages */

        private IProductService _productService;

        public ShopController(IProductService productService)
        {
            _productService = productService;
            // dependency injection
        }

        public IActionResult Index()
        {
            return View();
        }

        // EX ROUTE: products/category?page=2
        [HttpGet]
        [Route("products/{category?}")]
        public IActionResult List(string category, int page = 1)
        {
            /* this controller is for listing all the products in the app */
            /* also makes pagination operations */

            const int pageSize = 3; /* number of elements in a page */

            /* return all the products to the rendering */
            var productListModel = new ProductListViewModel()
            {
                PaginationInformation = new PageInfo()
                {
                    TotalItems = _productService.CountByCategory(category),
                    ItemsPerPage = pageSize,
                    CurrentPage = page,
                    CurrentCategory = category
                },
                Products = _productService.GetProductsByCategoryByPage(category, page, pageSize)
            };

            return View(productListModel);
        }

        public IActionResult Details(int? ID)
        {
            /* this controller will show details of a product
               ürünlerin detaylarını gösterir, ürün sayfası
             */

            if (ID == null)
            {
                // if there is no id data given, return not found
                return NotFound();
            }
            // else go fetch the product with the given id
            var theProduct = _productService.GetProductDetails((int)ID);
            // there might be NO PRODUCT with the given id
            if (theProduct == null)
            {
                // there is no such product
                return NotFound();
            }

            // in this case, product found and valid
            // return ProductDetailModel which includes categories

            return View(new ProductDetailsViewModel
            {
                Product = theProduct,
                Categories = theProduct.ProductCategories.Select(prop => prop.Category).ToList()
            });
        }
    }
}

ShopApp.WebUI/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstract;
using ShopApp.WebUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ShopApp.WebUI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            Debug.Write(RouteData.Values["category"]?.ToString().ToLower());
            return View(new CategoryListViewModel()
            {
                SelectedCategory = RouteData.Values["category"]?.ToString().ToLower(),
                Categories = _categoryService.GetAll()
            }); ;
        }
    }
}

ShopApp.WebUI/Views/Shop/Details.cshtml
@model ProductDetailsViewModel

<div class="row">
    <div class="col-md-3">
        <img src="~/img/@Model.Product.ImageURL" alt="@Model.Product.Name" class="img-fluid" />
    </div>
    <div class="col-md-9">
        <h1 class="mb-3 productTitle">
            @Model.Product.Name
        </h1>
        <hr />
        <!--Categories-->
        @foreach (var category in Model.Categories)
        {
            <a href="/products/@category.Name.ToLower()" class="btn btn-link p-0 mb-3">@category.Name</a>
        }

        <div class="productPrice mb-3 mt-3">
            <h4 class="text-primary mb-3">
                @Model.Product.Price <i class="fas fa-lira-sign"></i>
            </h4>
            <button type="submit" class="btn btn-primary btn-lg">Add to Cart</button>
        </div>
        <div class="row productDescription">
            <div class="col-md-12">
                <p class="p-4">
                    @Html.Raw(Model.Product.Description)
                </p>
            </div>
        </div>
    </div>
</div>

ShopApp.WebUI/Views/Shop/List.cshtml
@model ProductListViewModel

@{
    ViewData["Title"] = "Magic Shopping";
}

<div class="text-center">

    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryList")
        </div>
        <div class="col-md-9">

            <div class="row">
                @foreach (var product in Model.Products)
                {
                    <partial name="_product" model="@product" />
                }
            </div>

            <div page-model="@Model.PaginationInformation"></div>
        </div>
    </div>
</div>